### ISSUE TITLE
Can't connect using `BastionHostAuroraServerlessForward`

### ISSUE THREAD

**Issue by moltar** [moia-oss/bastion-host-forward#164]
I've setup `BastionHostAuroraServerlessForward` per instructions.

Then I run:

```sh
aws ssm start-session \
  --target i-x \
  --document-name AWS-StartPortForwardingSession \
  --parameters '{"portNumber": ["5432"], "localPortNumber":["5432"]}'
```

And get:

```
Starting session with SessionId: foo-060bbc90196b150bf
Port 5432 opened for sessionId foo-060bbc90196b150bf.
Waiting for connections...
```

Then I try to connect with a local client, and get the following error:

```
Connection to destination port failed, check SSM Agent logs.
```

After checking the logs (`/var/log/amazon/ssm/amazon-ssm-agent.log`) on the bastion, I get:

```
2021-11-27 08:15:50 ERROR [ssm-session-worker] [foo-060bbc90196b150bf]
[DataBackend] [pluginName=Port] Unable to dial connection to server: dial tcp :5432: connect: connection refused
```

However, if I install a `psql` client inside the bastion, I am able to connect to the RDS cluster just fine. So this rules out a networking issue.

Any ideas?

Thanks!

**Comment by moltar** [comment]
Hm, interesting, looked in the `/etc/haproxy/haproxy.cfg`, and what I see is:

```
listen database
  bind 0.0.0.0:-1.8881545897088582e+289
  timeout connect 10s
  timeout client 1m
  timeout server 1m
  mode tcp
  server service xxx.cluster-xxx.ap-northeast-1.rds.amazonaws.com:-1.8881545897088582e+289
```

Wonder where the `-1.8881545897088582e+289` value is coming from.

**Comment by moltar** [comment]
Looks like this is the issue: https://github.com/aws/aws-cdk/issues/2711

**Comment by moltar** [comment]
I'm going to close this issue, as I don't think it's anything to do with this repo / package.

If anyone runs into this, the fix mentioned here works: https://github.com/aws/aws-cdk/issues/2711#issuecomment-980542947

**Comment by moltar** [comment]
Actually this appears to be a real issue, and the proposed solution is here:

https://github.com/aws/aws-cdk/issues/2711#issuecomment-988230801

**Comment by snowiow** [comment]
I provided a fix here https://github.com/moia-oss/bastion-host-forward/pull/170. Can you check if that version would work with your ServerlessCluster?

**Comment by moltar** [comment]
Amazing! Can you do an alpha release on NPM? It's just installing TS from GH does not always work. Might need to be transpiled first.

**Comment by snowiow** [comment]
I can try. Let me look how it works and I come back to you if it's available :)

**Comment by snowiow** [comment]
ok alpha is released as 0.8.5-alpha.0 https://www.npmjs.com/package/@moia-oss/bastion-host-forward/v/0.8.5-alpha.0

**Comment by moltar** [comment]
Looks great.

I've deployed the fixed version and checked the user data on the instance, and it looks fine:

```
...

echo "listen database
  bind 0.0.0.0:5432
  timeout connect 10s

...
```

I tried connecting and that also works.

Thank you! 👊🏼

**Comment by snowiow** [comment]
nice, will create the real release then. Thanks for testing 👍
