### ISSUE TITLE
Bastion Host EBS encryption

### ISSUE THREAD

**Issue by glmourad** [moia-oss/bastion-host-forward#317]
Hi,

The construct is not compliant with the following Config rule once the EBS volume attached to the instance is not encrypted:
https://docs.aws.amazon.com/config/latest/developerguide/encrypted-volumes.html

Is it possible to add parameters in order to specify if volume is needed or not?
If can't remove the ebs volume I would say to add the "encrypted=True" option to the volume and optionally specify a KMS key.

Thanks in advance!

**Comment by snowiow** [comment]
Hi, we included this now into the bastion host for v2.0.0
