### ISSUE TITLE
Unable to create two bastion hosts

### ISSUE THREAD

**Issue by xird** [moia-oss/bastion-host-forward#368]
I have a CDK configuration that I've inherited from previous developers, and they've set up two bastion hosts:

```
    new BastionHostRDSForward(this, 'BastionHost', {
      name: 'BastionHost',
      rdsInstance: this.applicationDatabaseInstance,
      vpc: this.props.infra.vpc,
    });

    new BastionHostRDSForward(this, 'AnalyticsBastionHost', {
      name: 'AnalyticsBastionHost',
      rdsInstance: this.analyticsDatabaseInstance,
      vpc: this.props.infra.vpc,
    });
```
Trying to deploy this stack fails with an error saying "Launch template name already in use". One bastion host can be deployed successfully, if I comment one of them out.

This makes sense, since the launch template created for the first bastion host is called "ResourceLaunchTemplate". This looks like a default name, and creating another host fails since launch template names need to be unique on an account.

Any ideas on how to fix this?

**Comment by snowiow** [comment]
Hi, I tried it myself with this snippet and I couldn't reproduce it 
```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { BastionHostRDSForward } from '@moia-oss/bastion-host-forward'
import { InstanceClass, InstanceSize, InstanceType, Vpc } from 'aws-cdk-lib/aws-ec2';
import { DatabaseInstance, DatabaseInstanceEngine, PostgresEngineVersion } from 'aws-cdk-lib/aws-rds';

export class BastionTestStack extends cdk.Stack {
    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        const vpc = new Vpc(this, 'MyVpc', {
        });


      const db1 = new DatabaseInstance(this, 'db1', {
        instanceType: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.SMALL),
        engine: DatabaseInstanceEngine.postgres({
          version: PostgresEngineVersion.VER_15_4
        }),
        vpc,
      });

      const db2 = new DatabaseInstance(this, 'db2', {
        instanceType: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.SMALL),
        engine: DatabaseInstanceEngine.postgres({
          version: PostgresEngineVersion.VER_15_4
        }),
        vpc,
      });

        new BastionHostRDSForward(this, 'BastionHost', {
            name: 'BastionHost',
            rdsInstance: db1,
            vpc,
        });

        new BastionHostRDSForward(this, 'AnalyticsBastionHost', {
            name: 'AnalyticsBastionHost',
            rdsInstance: db2,
            vpc,
        });
    }
}
```
The launch template names for me are `BastionTestStackBastionHostLaunchTemplateE8FDE5FE` and `BastionTestStackAnalyticsBastionHostLaunchTemplate4E8AB865`. Could you check if there is a launch template in your account that wasn't cleaned up earlier and is causing the naming conflict and are you using the most current version "1.3.0"?

**Comment by snowiow** [comment]
[This looks like it was a problem in cdk once](https://github.com/aws/aws-cdk/pull/17766) so updating the library should hopefully fix the issue

**Comment by xird** [comment]
Still having the same problem:

- Updated dependencies:
  - "@moia-oss/bastion-host-forward": "^1.3.0",
  - "aws-cdk": "2.103.1",
  - "aws-cdk-lib": "2.103.1",
  - "constructs": "^10.3.0",
- Deleted node_modules and ran yarn install again
- Deployed the stack with a single bastion host

-> The newly created launch template is still stubbornly named "ResourceLaunchTemplate".

In any case, it's unlikely to be an issue with `bastion-host-forward`, so I'll keep digging in my stack definition. Thanks for your help.

**Comment by xird** [comment]
I've now created a minimal setup that reproduces the error. At least on my machine and the AWS account I'm using...

Would you mind trying to deploy this: https://github.com/xird/debug-stack

**Comment by snowiow** [comment]
sure, but I think the actual code is still missing in the repo?

**Comment by xird** [comment]
Ah. I managed to gitignore the lib directory. Fixed now.

**Comment by snowiow** [comment]
ah now I got it as well, but in that case you can add the following to your cdk.json under context like stated in the linked cdk PR: 
```
    "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true
```

Then it should also be enforced to generate unique names.

**Comment by xird** [comment]
I somehow missed the actual solution in the linked PR. Had a long week behind me I guess...

I got it working now, thanks a lot!
