### ISSUE TITLE
Aurora serverless support

### ISSUE THREAD

**Issue by gdelpu** [moia-oss/bastion-host-forward#80]
Hello,

I'm really interested in your construct. I'm trying to use it with an aurora Serverless database, but with no success so far. Do you have already done that?

**Comment by snowiow** [comment]
Hi, sadly not. We work mostly in eu-central-1, which doesn't have aurora serverless support yet. If you don't find success with this construct, maybe the new [rds-proxy](https://aws.amazon.com/rds/proxy) does.

**Comment by snowiow** [comment]
Hi again, Serverless Aurora Support was now merged via #124 and is available from version 0.8.0 onward.
