### ISSUE TITLE
Make it possible to adjust haproxy timeout

### ISSUE THREAD

**Issue by libre-man** [moia-oss/bastion-host-forward#84]
It would be really nice if it were possible to adjust the timeout used by haproxy.

Our usecase for this is that we use our bastion to do management tasks on our database, however when doing this we sometimes write some code which causes the connection to timeout, which is really annoying.

**Comment by snowiow** [comment]
hi, we set 3 kinds of timeouts in the haproxy config atm:

```
timeout connect 10s
timeout client 1m
timeout server 1m
```

do you need to set one or all of them? Thanks in advance

**Comment by libre-man** [comment]
Hi!

I would really like to at least set the `client` timeout (I think this would solve my problem that it is not possible to have a long running `psql` shell without timing out).

**Comment by snowiow** [comment]
ok, will make that parameter configurable then 👍

**Comment by snowiow** [comment]
both of your requests are available in 0.6.0
